services:
  web:
    build: .
    environment:
      - FLAG=ptm{fake_flag}
      - HEADLESS_URL=http://headless:5000
      - CHALLENGE_HOST=http://web:3000/
      - HEADLESS_SECRET=idkdoesntmatterifirevealit
      - DB=postgres://imgplace:imgplace@db/imgplace
    ports:
      - 3000:3000
  headless:
    image: cybersecnatlab/challenge-headless:latest
    environment:
        AUTH_TOKEN: idkdoesntmatterifirevealit
  db:
    image: "docker.io/postgres:17-alpine"
    volumes: 
     - type: tmpfs
       target: /var/lib/postgresql/data/
    environment:
        - POSTGRES_DB=imgplace
        - POSTGRES_USER=imgplace
        - POSTGRES_PASSWORD=imgplace