services:
  gosecureit:
    build:
      dockerfile: Dockerfile
    ports:
      - "2301:2301"
    command: ./GoSecureIt
    environment:
      flag: "ptm{fake_flag}"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "a_super_secret_password"
      POSTGRES_DB: "chall"
    depends_on:
      - postgres

  postgres:
      image: postgres:latest
      container_name: postgres
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "a_super_secret_password"
        POSTGRES_DB: "chall"