

riga1 = "brybefejnkidosboguihagsepxeywufiazxoxzbmtjrcfsknpkldhzjauxayobidvhnaqgbxzfsjyrwaanndfompthvsbqkgxmqelqaifrfkfmonzvnkmrgmhccunoir"
riga2 = "xxxbhafmrsbuseiwnwiyibbprvienxuqromdwofcupvupdewoyjj" 
riga3 = "ptjilemtmvowacennoaykdzojeqevimbbfmycmmgvbfzncavp" 
riga4 = "ksdpsbjmgekyyrdzxppurwcomfjvnoouvimxjbcdbwuooxhgcjeuivfydlfucajyibhlvcsijwethshnwbmvkftvwoosexg" 
riga5 = "rdgvipgcyliyrswfpvbrhmrgtzevpdbuggfvvlbihwbr" 
riga6 = "pemzmblrzasbsuecggofxehwexdqowqwpbwlwqrlynupg" 
riga7 = "ofyngrbkaldjxznvvijkpecfgdbwrkmgjinsluahzyfckykgkwlmrhrubjyfmftlafujmbijvwolwpuayyxybdolmfquldxfmvxbzliwixespnzaxjyrmrhfhozizgfvan"


