services:
  age_calculator_pro:
    image: cybersecnatlab/challenge-jail@sha256:7bf77225063b039960f654307cf5d6f977f892ff548606357a2e8fe8067d0a88
    restart: unless-stopped
    init: true
    privileged: true
    volumes:
      - './build/age_calculator_pro:/home/user/chall:ro'
    ports:
      - '1337:1337'
    environment:
      - 'FLAG=flag{fake_flag}'
