services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "31347:8080"
    environment:
      PORT: 8080
      FLAG: flag{dummy}
      COOKIE_SECRET: secret # different on server